Wazo 2185 linefeatures search
wazo-platform/xivo-dao pull request #130
Opened 2021-08-06 18:04 UTC by ja0x

2021-08-09 17:06 UTC, fblackburn1 commented
rebase with master to include new zuul linters check

2021-08-11 13:56 UTC, fblackburn1 requested changes
## Blockers
* You add a lot of unused code (dead code) with `can_inherit=True`. It's not in our practice to do this kind of work. It add complexity to read/debug and maintains.
  * Moreover, tests are missing on this part too, nobody except you know if it work or not  
* unit tests are missing for the endpoint_sip `query_options_value` method. They should cover all corner cases scenarios.
* 
## Warnings
* be careful with your commit message length, you can read guideline in the wiki about max length
* You can rebase your branch **before** moving to review. It will avoid useless commit and be easier to validate. I can show you how, if you want.

## Comments
Do you have benchmark to compare before/after?
  * With > 1000 lines/endpoint_sip
  * With 1 line/endpoint_sip
Did you confirm this behavior with a PO (i.e. do not search through inherited template)?

2021-08-11 13:56 UTC, fblackburn1 commented on xivo_dao/alchemy/tests/test_linefeatures.py
> +        ))
Each test should test ~one thing
Split test for each endpoint
Moreover tests should remain simple and explicit and maintainable by junior/senior. There is no difference between testing 10 lines or 2. Only a lot of loop and unnecessary complexity are added. Don't hesitate to hardcode value to improve readability (only for tests...)

2021-08-11 13:56 UTC, fblackburn1 commented on xivo_dao/resources/line/search.py
> +            extens = parameters.pop('exten').split(',')
There is a reason to search by mutli exten? Ticket doesn't mention that
search example by single exten: https://github.com/wazo-platform/xivo-dao/commit/88a371e12691d810b402b8729b7d60b36b56b6ae

2021-08-11 13:59 UTC, fblackburn1 commented on xivo_dao/alchemy/endpoint_sip.py
> +        check_sections = sections if isinstance(sections, list) else [sections]
I don't see the point to search an option in many sections. There is no test and use case in the PR too

2021-09-01 08:16 UTC, rgarrigue commented
recheck

2021-11-08 20:02 UTC, fblackburn1 requested changes
As discussed
* A documentation of small description of materialized with the PJSIP context would help to understand this part of code
* Check if you can use sqlalchemy-utils view
* Also, when you adapt external code, do not forget to add credit
  ex: `# Adapted from http://...`

2021-11-22 20:52 UTC, fblackburn1 approved these changes
:tada:

2021-11-22 21:14 UTC, merged