Validate parameters used for user search
wazo-platform/xivo-dao pull request #213
Opened 2023-05-26 14:51 UTC by xxbillouxx

2023-05-29 13:59 UTC, sduthil commented on xivo_dao/resources/user/persistor.py
> +        self.user_search.config.column_for_sorting(parameters['order'])
This violates encapsulation.

Other possible solutions:
1. extract the validation logic from outside the `SearchSystem` and use it in both places.
2. push the manual collation logic down to `SearchSystem` (this one has my preference)

2023-05-29 13:59 UTC, sduthil requested changes

2023-05-29 13:59 UTC, sduthil commented on xivo_dao/resources/user/persistor.py
> +        self.user_search.config.column_for_sorting(parameters['order'])
This violates encapsulation.

Other possible solutions:
1. extract the validation logic from outside the `SearchSystem` and use it in both places.
2. push the manual collation logic down to `SearchSystem` (this one has my preference)

2023-05-30 10:33 UTC, jfbourque commented
recheck

2023-05-30 13:44 UTC, sduthil approved these changes

2023-05-30 13:51 UTC, merged