Add feature extension
wazo-platform/xivo-dao pull request #236
Opened 2023-07-28 20:37 UTC by xxbillouxx

2023-08-01 19:18 UTC, xxbillouxx commented
recheck

2023-08-01 20:01 UTC, xxbillouxx commented
recheck

2023-08-02 13:29 UTC, fblackburn1 commented
recheck

2023-08-03 13:35 UTC, xxbillouxx commented
recheck

2023-08-08 18:00 UTC, pc-m requested changes
Pretty impressed by all the work you've done for this refactor. Good job

2023-08-08 18:50 UTC, xxbillouxx commented on xivo_dao/resources/feature_extension/database.py
> +    return exten.strip('_.')
@pc-m better version used now

2023-08-08 18:51 UTC, xxbillouxx commented on xivo_dao/resources/func_key/hint_dao.py
> +    return session.query(FeatureExtension.exten).filter(and_(
@pc-m `and_` removed

2023-08-08 18:51 UTC, xxbillouxx commented on xivo_dao/alchemy/extension.py
> +    dialpattern = relationship(
@pc-m reformated now

2023-08-08 18:51 UTC, xxbillouxx commented on xivo_dao/alchemy/feature_extension.py
> +        Index('feature_extension__idx__uuid', 'uuid'),
@pc-m explicit index for uuid removed now

2023-08-08 18:52 UTC, xxbillouxx commented on xivo_dao/alchemy/feature_extension.py
> +    def clean_exten(self):
@pc-m `clean_exten` implementation removed and `clean_extension` used instead

2023-08-08 18:53 UTC, xxbillouxx commented on xivo_dao/alchemy/tests/test_feature_extension.py
> +        assert_that(extension.is_pattern(), equal_to(True))
@pc-m as you suggested, `clean_extension` from `xivo-lib-python` used

2023-08-08 18:54 UTC, xxbillouxx commented on xivo_dao/resources/feature_extension/__init__.py
> +# Copyright 2023 The Wazo Authors  (see the AUTHORS file)
@pc-m `__init__.py` files cleaned now

2023-08-08 18:55 UTC, xxbillouxx commented on xivo_dao/resources/feature_extension/model.py
> +
@pc-m content moved into `database.py` as used only here

2023-08-08 18:56 UTC, xxbillouxx commented on xivo_dao/resources/func_key/hint_dao.py
> +            and_(
@pc-m `and_` removed now as suggested

2023-08-09 13:55 UTC, pc-m requested changes

2023-08-09 13:55 UTC, pc-m commented on xivo_dao/alchemy/extension.py
> +    dialpattern = relationship(
This change needs to be applied to other relationships in this file as well ;)

2023-08-10 12:26 UTC, xxbillouxx commented on xivo_dao/alchemy/extension.py
> +    dialpattern = relationship(
@pc-m fixed

2023-08-14 19:07 UTC, pc-m approved these changes

2023-08-14 20:01 UTC, pc-m commented
recheck

2023-08-14 20:17 UTC, merged