incall: avoid searching through ID fields
wazo-platform/xivo-dao pull request #245
Opened 2023-10-04 15:29 UTC by pc-m

the user does not know the incall id or the user id. Allowing this only leads to poor user experience when searching for 1001 and ending up with 3 results

incall exten 1001
incall id 1001
incall with a user destination with id 1001

Also searching in user_id is very expensive at the moment

2023-10-04 15:30 UTC, pc-m commented
Note that I've executed confd test_incalls.py and test_incall_extension.py with this change

2023-10-06 17:19 UTC, fblackburn1 requested changes
Quick look at the incall model, it seems that the user_id property is now unused
Can you take a look and also remove associated tests

2023-10-06 19:27 UTC, pc-m commented
> Quick look at the incall model, it seems that the user_id property is now unused Can you take a look and also remove associated tests

Done. A did not find confd tests that relied on the `user_id` expression and I executed the test_incalls.py and test_incall_extensions.py tests locally

2023-10-06 20:27 UTC, fblackburn1 approved these changes

2023-10-06 20:28 UTC, fblackburn1 approved these changes

2023-10-06 20:42 UTC, merged