Pull request for WAZO-3685-user-outgoing-callerids
wazo-platform/xivo-dao pull request #276
Opened 2024-04-19 14:52 UTC by fblackburn1

2024-04-19 16:06 UTC, fblackburn1 commented on xivo_dao/alchemy/incall.py
> +    # NOTE(fblackburn): This field is a workaround and MUST never be exposed to the API
Updated (added ticket in the comment): https://wazo-dev.atlassian.net/browse/WAZO-3715

2024-04-19 17:11 UTC, pc-m requested changes

2024-04-22 15:42 UTC, pc-m approved these changes

2024-04-22 15:45 UTC, fblackburn1 commented on xivo_dao/resources/incall/persistor.py
> +        if not (main_exists or user_destination):
Fixed: user restriction has been removed

2024-04-22 15:56 UTC, merged

2024-04-22 15:56 UTC, fblackburn1 commented
fail not related. I'll investigate on the side. But merging for not to avoid more delays